<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>px4_frequency_sweep</name>
  <version>0.1.0</version>
  <description>A configurable PX4 ROS 2 external mode for frequency-sweep system-identification experiments.</description>
  <maintainer email="wee733@users.noreply.github.com">wee733</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>eigen3_cmake_module</buildtool_depend>
  <build_export_depend>eigen3_cmake_module</build_export_depend>

  <depend>eigen</depend>
  <depend>rclcpp</depend>
  <depend>px4_ros2_cpp</depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
